<a href="https://colab.research.google.com/github/Raajarapu/COLAB_practice/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Feature Scaling and Normalization
Explanation: Feature scaling and normalization are used for numerical datasets to bring features to a common scale. This ensures machine learning models perform optimally, especially when algorithms are sensitive to feature magnitudes.


# Standard Scaler
Standard Scaler: Scales the data to have zero mean and unit variance.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Numerical Dataset
numerical_data = pd.DataFrame({
    'Feature1': [1, 2, 3, np.nan, 5],
    'Feature2': [100, 200, 300, 400, 500]
}).fillna(0)  # Fill NaNs with 0 for demonstration purposes

# Standard Scaler
scaler = StandardScaler()
standard_scaled = scaler.fit_transform(numerical_data)
print("Standard Scaled:\n", standard_scaled)

Standard Scaled:
 [[-0.69748583 -1.41421356]
 [-0.11624764 -0.70710678]
 [ 0.46499055  0.        ]
 [-1.27872403  0.70710678]
 [ 1.62746694  1.41421356]]


# MinMax Scaler
MinMax Scaler: Scales features to lie within a defined range (usually between 0 and 1).

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Numerical Dataset
numerical_data = pd.DataFrame({
    'Feature1': [1, 2, 3, np.nan, 5],
    'Feature2': [100, 200, 300, 400, 500]
}).fillna(0)  # Fill NaNs with 0 for demonstration purposes

# MinMax Scaler
scaler = MinMaxScaler()
minmax_scaled = scaler.fit_transform(numerical_data)
print("MinMax Scaled:\n", minmax_scaled)

MinMax Scaled:
 [[0.2  0.  ]
 [0.4  0.25]
 [0.6  0.5 ]
 [0.   0.75]
 [1.   1.  ]]


# MaxAbs Scaler
MaxAbs Scaler: Scales features by their maximum absolute value while maintaining sparsity in the data.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MaxAbsScaler

# Numerical Dataset
numerical_data = pd.DataFrame({
    'Feature1': [1, 2, 3, np.nan, 5],
    'Feature2': [100, 200, 300, 400, 500]
}).fillna(0)  # Fill NaNs with 0 for demonstration purposes

# MaxAbs Scaler
scaler = MaxAbsScaler()
maxabs_scaled = scaler.fit_transform(numerical_data)
print("MaxAbs Scaled:\n", maxabs_scaled)

MaxAbs Scaled:
 [[0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.  0.8]
 [1.  1. ]]


# Robust Scaler
Robust Scaler: Scales features using the median and interquartile range, which makes it robust to outliers.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler

# Numerical Dataset
numerical_data = pd.DataFrame({
    'Feature1': [1, 2, 3, np.nan, 5],
    'Feature2': [100, 200, 300, 400, 500]
}).fillna(0)  # Fill NaNs with 0 for demonstration purposes

# Robust Scaler
scaler = RobustScaler()
robust_scaled = scaler.fit_transform(numerical_data)
print("Robust Scaled:\n", robust_scaled)

Robust Scaled:
 [[-0.5 -1. ]
 [ 0.  -0.5]
 [ 0.5  0. ]
 [-1.   0.5]
 [ 1.5  1. ]]


# Normalizer
Normalizer: Scales each sample to have a unit norm, making it scale-invariant.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Normalizer

# Numerical Dataset
numerical_data = pd.DataFrame({
    'Feature1': [1, 2, 3, np.nan, 5],
    'Feature2': [100, 200, 300, 400, 500]
}).fillna(0)  # Fill NaNs with 0 for demonstration purposes

# Normalizer
scaler = Normalizer()
normalized = scaler.fit_transform(numerical_data)
print("Normalized:\n", normalized)

Normalized:
 [[0.0099995 0.99995  ]
 [0.0099995 0.99995  ]
 [0.0099995 0.99995  ]
 [0.        1.       ]
 [0.0099995 0.99995  ]]


# 2. Encoding for Categorical Data

OneHotEncoder: Creates binary columns for each unique category. Each column represents a category.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

# Categorical Dataset
categorical_data = pd.DataFrame({
    'Category1': ['Low', 'Medium', np.nan, 'High', 'Low'],
    'Category2': ['A', 'B', 'C', 'A', np.nan]
}).fillna('Missing')  # Replace missing values with 'Missing' for demonstration

# OneHotEncoder
encoder = OneHotEncoder()
onehot_encoded = encoder.fit_transform(categorical_data).toarray()
print("OneHot Encoded:\n", onehot_encoded)

OneHot Encoded:
 [[0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1.]]


LabelEncoder: Converts categories into numbers (e.g., "Low" becomes 0, "Medium" becomes 1, "High" becomes 2).

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

# Categorical Dataset
categorical_data = pd.DataFrame({
    'Category1': ['Low', 'Medium', np.nan, 'High', 'Low'],
    'Category2': ['A', 'B', 'C', 'A', np.nan]
}).fillna('Missing')  # Replace missing values with 'Missing' for demonstration

# LabelEncoder (for single column encoding)
le = LabelEncoder()
label_encoded = le.fit_transform(categorical_data['Category1'])
print("Label Encoded Category1:\n", label_encoded)

Label Encoded Category1:
 [1 2 3 0 1]


OrdinalEncoder: Encodes categories as ordered numbers, suitable for ordinal data (e.g., "Low", "Medium", "High").

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
import numpy as np

# Categorical Dataset
categorical_data = pd.DataFrame({
    'Category1': ['Low', 'Medium', np.nan, 'High', 'Low'],
    'Category2': ['A', 'B', 'C', 'A', np.nan]
}).fillna('Missing')  # Replace missing values with 'Missing' for demonstration

# OrdinalEncoder with 'Missing' included in categories
oe = OrdinalEncoder(categories=[['Missing', 'Low', 'Medium', 'High']])  # Include 'Missing' explicitly
ordinal_encoded = oe.fit_transform(categorical_data[['Category1']])
print("Ordinal Encoded Category1:\n", ordinal_encoded)

Ordinal Encoded Category1:
 [[1.]
 [2.]
 [0.]
 [3.]
 [1.]]


# SimpleImputer
What it does: Replaces missing values with a single constant or statistical measure (mean, median, most frequent, or constant value).
Use case: Suitable when missing values are missing at random and the dataset has a predictable distribution.

In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

# Numerical Dataset with Missing Values
numerical_data_with_missing = pd.DataFrame({
    'Feature1': [1, np.nan, 3, np.nan, 5],
    'Feature2': [100, 200, np.nan, 400, 500]
})

# Simple Imputer (fill missing values with mean)
simple_imputer = SimpleImputer(strategy='mean')
simple_imputed = simple_imputer.fit_transform(numerical_data_with_missing)
print("Simple Imputed:\n", simple_imputed)

Simple Imputed:
 [[  1. 100.]
 [  3. 200.]
 [  3. 300.]
 [  3. 400.]
 [  5. 500.]]


# KNNImputer
What it does: Uses k-Nearest Neighbors to impute missing values by averaging the values of the nearest k samples with similar features.
Use case: Suitable when missing values have a relationship with surrounding data points and when data follows local patterns.


In [ ]:
from sklearn.impute import KNNImputer
import pandas as pd
import numpy as np

# Numerical Dataset with Missing Values
numerical_data_with_missing = pd.DataFrame({
    'Feature1': [1, np.nan, 3, np.nan, 5],
    'Feature2': [100, 200, np.nan, 400, 500]
})

# KNNImputer (use nearest neighbors to fill missing values)
knn_imputer = KNNImputer(n_neighbors=2)
knn_imputed = knn_imputer.fit_transform(numerical_data_with_missing)
print("KNN Imputed:\n", knn_imputed)

KNN Imputed:
 [[  1. 100.]
 [  3. 200.]
 [  3. 300.]
 [  3. 400.]
 [  5. 500.]]
